name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: MAC Text
      id: mac-text
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: MAC Text
        setup-command: ''
        command: python exercise3.py
        input: "-1"
        expected-output: MAC Manufacturer Program
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Dashes Text
      id: dashes-text
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Dashes Text
        setup-command: ''
        command: python exercise3.py
        input: "-11"
        expected-output: "------------------------"
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Prompt Text
      id: prompt-text
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Prompt Text
        setup-command: ''
        command: python exercise3.py
        input: "-111"
        expected-output: 'Enter the first 6 hex values of the MAC address (format
          as XX:XX:XX): '
        comparison-method: contains
        timeout: 1
        max-score: 1
    - name: Oracle Test Case
      id: oracle-test-case
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Oracle Test Case
        setup-command: ''
        command: python exercise3.py
        input: '00:00:17'
        expected-output: For 00:00:17 the MAC manufacturer is Oracle.
        comparison-method: contains
        timeout: 1
        max-score: 4
    - name: Intel
      id: intel
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Intel
        setup-command: ''
        command: python exercise3.py
        input: 00:07:E9
        expected-output: For 00:07:E9 the MAC manufacturer is Intel Corporation.
        comparison-method: contains
        timeout: 1
        max-score: 4
    - name: Microsoft
      id: microsoft
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Microsoft
        setup-command: ''
        command: python exercise3.py
        input: '04:27:28'
        expected-output: For 04:27:28 the MAC manufacturer is Microsoft Corporation.
        comparison-method: contains
        timeout: 1
        max-score: 4
    - name: Apple
      id: apple
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Apple
        setup-command: ''
        command: python exercise3.py
        input: 04:26:65
        expected-output: For 04:26:65 the MAC manufacturer is Apple, Inc.
        comparison-method: contains
        timeout: 1
        max-score: 4
    - name: Huawei
      id: huawei
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Huawei
        setup-command: ''
        command: python exercise3.py
        input: 04:33:89
        expected-output: For 04:33:89 the MAC manufacturer is Huawei Technologies
          Co.,Ltd.
        comparison-method: contains
        timeout: 1
        max-score: 4
    - name: Cisco
      id: cisco
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Cisco
        setup-command: ''
        command: python exercise3.py
        input: 00:00:0C
        expected-output: For 00:00:0C the MAC manufacturer is Cisco Systems, Inc.
        comparison-method: contains
        timeout: 1
        max-score: 4
    - name: Not Valid Value
      id: not-valid-value
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Not Valid Value
        setup-command: ''
        command: python exercise3.py
        input: '21'
        expected-output: For 21 the MAC manufacturer is Unknown.
        comparison-method: contains
        timeout: 1
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAC-TEXT_RESULTS: "${{steps.mac-text.outputs.result}}"
        DASHES-TEXT_RESULTS: "${{steps.dashes-text.outputs.result}}"
        PROMPT-TEXT_RESULTS: "${{steps.prompt-text.outputs.result}}"
        ORACLE-TEST-CASE_RESULTS: "${{steps.oracle-test-case.outputs.result}}"
        INTEL_RESULTS: "${{steps.intel.outputs.result}}"
        MICROSOFT_RESULTS: "${{steps.microsoft.outputs.result}}"
        APPLE_RESULTS: "${{steps.apple.outputs.result}}"
        HUAWEI_RESULTS: "${{steps.huawei.outputs.result}}"
        CISCO_RESULTS: "${{steps.cisco.outputs.result}}"
        NOT-VALID-VALUE_RESULTS: "${{steps.not-valid-value.outputs.result}}"
      with:
        runners: mac-text,dashes-text,prompt-text,oracle-test-case,intel,microsoft,apple,huawei,cisco,not-valid-value
